spring:
  h2.console:
    enabled: true
    path: '/console'
  jpa:
    hibernate:
      ddl-auto: validate

google:
  recaptcha:
    key:
      site: '6Lf8j4EfAAAAACpAlC2q6oka4bZobAzkMc2vi-N6'
      secret: '6Lf8j4EfAAAAAC2pDmscifexX5n-vGEmuoYUbh-u'


## HTTPS config
server:
  port: 443
  ssl:
    key-password: 123456
    key-store-password: 123456
    key-store: 'src/main/resources/https/keystore.jks'
  servlet:
    context-path: '/car-rental'


